limits:
  show_border: true
  message: ยง4You've hit the world border.
  sound:
    name: entity.blaze.hurt
    pitch: 1.0
    volume: 4.0
    category: MASTER

borders:
#  world:
#    ==: de.mccityville.worldborder.border.VerticalLimitedCuboidWorldBorder
#    center_x: 0
#    center_z: 0
#    radius: 25
#    max_y: 255
